name: dbt CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      # ✅ DEBUG (prove secrets exist)
      - name: Debug secrets
        run: |
          echo "ACCOUNT=${{ secrets.SF_ACCOUNT }}"
          echo "USER=${{ secrets.SF_USER }}"

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          tpch_analytics:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: "${{ secrets.SF_ACCOUNT }}"
                user: "${{ secrets.SF_USER }}"
                password: "${{ secrets.SF_PASSWORD }}"
                role: "DBT_ROLE"
                database: "DBT_DEV"
                warehouse: "COMPUTE_WH"
                schema: "PUBLIC"
                threads: 4
          EOF

      - name: dbt deps
        run: dbt deps

      - name: dbt build
        run: dbt build